CREATE TABLE IF NOT EXISTS `pods` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `domain` varchar(100) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `score` tinyint(3) unsigned DEFAULT '10',
  `adminrating` decimal(4,2) DEFAULT '10.00',
  `userrating` decimal(4,2) DEFAULT '10.00',
  `whois` varchar(50) DEFAULT NULL,
  `hidden` varchar(3) DEFAULT 'yes',
  `ip` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `lat` varchar(50) DEFAULT NULL,
  `long` varchar(50) DEFAULT NULL,
  `connection` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `ipv6` varchar(50) DEFAULT NULL,
  `secure` varchar(50) DEFAULT NULL,
  `sslvalid` varchar(50) DEFAULT NULL,
  `Hgitdate` datetime DEFAULT NULL,
  `Hgitref` varchar(50) DEFAULT NULL,
  `Hruntime` varchar(50) DEFAULT NULL,
  `Hencoding` varchar(50) DEFAULT NULL,
  `pingdomurl` varchar(50) DEFAULT NULL,
  `pingdomlast` varchar(50) DEFAULT NULL,
  `monthsmonitored` int(11) DEFAULT NULL,
  `signup` tinyint(4) DEFAULT NULL,
  `total_users` int(11) DEFAULT NULL,
  `active_users_halfyear` int(11) DEFAULT NULL,
  `active_users_monthly` int(11) DEFAULT NULL,
  `local_posts` int(11) DEFAULT NULL,
  `uptimelast7` decimal(5,2) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `responsetimelast7` varchar(50) DEFAULT NULL,
  `dateUpdated` datetime DEFAULT NULL,
  `dateLaststats` datetime DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  `longversion` varchar(20) DEFAULT NULL,
  `shortversion` varchar(20) DEFAULT NULL,
  `masterversion` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `domain` (`domain`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;


CREATE TABLE IF NOT EXISTS `rating_comments` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `domain` varchar(50) NOT NULL,
  `comment` varchar(50) DEFAULT NULL,
  `admin` tinyint(1) DEFAULT '0',
  `pod_id` int(11) DEFAULT NULL,
  `rating` tinyint(3) unsigned DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `userurl` varchar(50) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `admin` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `userurl` varchar(50) DEFAULT NULL,
  `userpod` varchar(50) DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
