CREATE TABLE pods (
 id bigint UNIQUE PRIMARY KEY,
 domain varchar(50) UNIQUE NOT NULL,
 name varchar(50),
 score int DEFAULT 10,
 adminrating decimal DEFAULT 10,
 userrating decimal DEFAULT 10,
 whois varchar(50),
 hidden varchar(10) DEFAULT 'yes',
 ip varchar(50),
 ptr varchar(50),
 country varchar(50),
 city varchar(50),
 state varchar(50), 
 lat varchar(50),
 `long` varchar(50),
 connection varchar(50),
 postalcode varchar(50),
 email varchar(50),
 ipv6 varchar(50),
 secure varchar(50),
 sslvalid varchar(50),
 Hgitdate varchar(50),
 Hgitref varchar(50),
 Hruntime varchar(50),
 Hencoding varchar(50),
 pingdomurl varchar(50),
 pingdomlast varchar(50),
 monthsmonitored int,
 signup int,
 total_users int, 
 active_users_halfyear int,
 active_users_monthly int,
 local_posts int,
 uptimelast7 numeric(5,2),
 status varchar(50),
 responsetimelast7 varchar(50),
 dateUpdated datetime,
 dateLaststats datetime,
 dateCreated datetime
);
CREATE TABLE rating_comments (
 id bigint UNIQUE PRIMARY KEY,
 domain varchar(50) NOT NULL,
 comment varchar(50),
 admin varchar(50), 
 pod_id int,
 rating int,
 username varchar(50),
 userurl varchar(50),
 date datetime
);
CREATE TABLE users (
 id bigint UNIQUE PRIMARY KEY,
 admin int NOT NULL,
 username varchar(50) UNIQUE NOT NULL,
 password varchar(50) NOT NULL,
 userurl varchar(50),
 userpod varchar(50),
 dateCreated datetime
);
